exchanges:
  - name: "payloads_topic"
    type: "topic"
    persisted: true
  - name: "events_topic"
    type: "topic"
    persisted: true

queues:
  - name: "payload_queue"
    durable: true
    exclusive: false
    bindings:
      - routing_key: "*.payload.#"
        exchange: "payloads_topic"
  - name: "event_queue"
    durable: true
    exclusive: false
    bindings:
      - routing_key: "*.event.#"
        exchange: "events_topic"