image: golang:1.18-stretch

test:
  before_script:
    - git config --global url.https://oauth2:"${GITLAB_TOKEN}"@gitlab.kardinal.ai/.insteadOf https://gitlab.kardinal.ai/
  script:
    - if [ -n "$(gofmt -l .)" ]; then gofmt -d .; exit 1; fi
    - go vet ./...
    - go test -race $(go list ./... | grep -v /vendor/) -v -coverprofile=coverage.out
    - go tool cover -func=coverage.out
