stages:
  - test

TEST-library:
  stage: test
  image: golang:1.20-alpine
  before_script:
    - apk --no-cache add build-base
  script:
    # Enable CGO
    - export CGO_ENABLED=1
    # go formatting analysis
    - /bin/sh -c 'if [ -n "$(gofmt -l .)" ]; then gofmt -d .; exit 1; fi'
    # GO code quality analysis
    - go vet ./...
    # GO Unit Testing
    - go test -race $(go list ./... | grep -v /vendor/) -v -coverprofile=coverage.out
    - go tool cover -func=coverage.out
  coverage: /\s+\(statements\)\s+(\d+.\d+\%)/

TEST-lint:
  stage: test
  image: golangci/golangci-lint:v1.52-alpine
  script:
    - golangci-lint run -v